/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: cmaginot <cmaginot@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/06/06 15:21:41 by cmaginot          #+#    #+#             */
/*   Updated: 2021/06/19 16:21:18 by cmaginot         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */
#include "includes/ft_printf.h"
#include <stdio.h>

int main()
{
    int     i;
    char    c;
    char    *s;

    i = 42;
    c = 'c';
    s = "coucou";

    printf("|test printf ()        :|\n");
    ft_printf("|test ft_printf ()     :|\n");
    ft_printf("|------------------------\\\n");
    printf("|test printf (i)       :%i|\n", i);
    ft_printf("|test ft_printf (i)    :%i|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (0i)      :%0i|\n", i);
    ft_printf("|test ft_printf (0i)   :%0i|\n", i);
    ft_printf("|--------------------------\\\n");
    printf("|test printf ( i)      :% i|\n", i);
    ft_printf("|test ft_printf ( i)   :% i|\n", i);
    ft_printf("|--------------------------|\n");
    printf("|test printf (+i)      :%+i|\n", i);
    ft_printf("|test ft_printf (+i)   :%+i|\n", i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5i)      :%5i|\n", i);
    ft_printf("|test ft_printf (5i)   :%5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05i)     :%05i|\n", i);
    ft_printf("|test ft_printf (05i)  :%05i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5i)     :%-5i|\n", i);
    ft_printf("|test ft_printf (-5i)  :%-5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( 5i)     :% 5i|\n", i);
    ft_printf("|test ft_printf ( 5i)  :% 5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+5i)     :%+5i|\n", i);
    ft_printf("|test ft_printf (+5i)  :%+5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( 05i)    :% 05i|\n", i);
    ft_printf("|test ft_printf ( 05i) :% 05i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+05i)    :%+05i|\n", i);
    ft_printf("|test ft_printf (+05i) :%+05i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( -5i)    :% -5i|\n", i);
    ft_printf("|test ft_printf ( -5i) :% -5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+-5i)    :%+-5i|\n", i);
    ft_printf("|test ft_printf (+-5i) :%+-5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (0 5i)    :%0 5i|\n", i);
    ft_printf("|test ft_printf (0 5i) :%0 5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (0+5i)    :%0+5i|\n", i);
    ft_printf("|test ft_printf (0+5i) :%0+5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (- 5i)    :%- 5i|\n", i);
    ft_printf("|test ft_printf (- 5i) :%- 5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-+5i)    :%-+5i|\n", i);
    ft_printf("|test ft_printf (-+5i) :%-+5i|\n", i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-+*i)    :%-+*i|\n", 10, i);
    ft_printf("|test ft_printf (-+*i) :%-+*i|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (+*i)     :%+*i|\n", 10, i);
    ft_printf("|test ft_printf (+*i)  :%+*i|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0+*i)    :%0+*i|\n", 10, i);
    ft_printf("|test ft_printf (0+*i) :%0+*i|\n", 10, i);
    ft_printf("|---------------------------------|\n");

    printf("|test printf (.5i)       :%.5i|\n", i);
    ft_printf("|test ft_printf (.5i)    :%.5i|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (0.5i)      :%0.5i|\n", i);
    ft_printf("|test ft_printf (0.5i)   :%0.5i|\n", i);
    ft_printf("|--------------------------\\\n");
    printf("|test printf ( .5i)      :% .5i|\n", i);
    ft_printf("|test ft_printf ( .5i)   :% .5i|\n", i);
    ft_printf("|--------------------------|\n");
    printf("|test printf (+.5i)      :%+.5i|\n", i);
    ft_printf("|test ft_printf (+.5i)   :%+.5i|\n", i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5.5i)      :%5.5i|\n", i);
    ft_printf("|test ft_printf (5.5i)   :%5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05.5i)     :%05.5i|\n", i);
    ft_printf("|test ft_printf (05.5i)  :%05.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5.5i)     :%-5.5i|\n", i);
    ft_printf("|test ft_printf (-5.5i)  :%-5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( 5.5i)     :% 5.5i|\n", i);
    ft_printf("|test ft_printf ( 5.5i)  :% 5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+5.5i)     :%+5.5i|\n", i);
    ft_printf("|test ft_printf (+5.5i)  :%+5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( 05.5i)    :% 05.5i|\n", i);
    ft_printf("|test ft_printf ( 05.5i) :% 05.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+05.5i)    :%+05.5i|\n", i);
    ft_printf("|test ft_printf (+05.5i) :%+05.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( -5.5i)    :% -5.5i|\n", i);
    ft_printf("|test ft_printf ( -5.5i) :% -5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+-5.5i)    :%+-5.5i|\n", i);
    ft_printf("|test ft_printf (+-5.5i) :%+-5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (0 5.5i)    :%0 5.5i|\n", i);
    ft_printf("|test ft_printf (0 5.5i) :%0 5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (0+5.5i)    :%0+5.5i|\n", i);
    ft_printf("|test ft_printf (0+5.5i) :%0+5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (- 5.5i)    :%- 5.5i|\n", i);
    ft_printf("|test ft_printf (- 5.5i) :%- 5.5i|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-+5.5i)    :%-+5.5i|\n", i);
    ft_printf("|test ft_printf (-+5.5i) :%-+5.5i|\n", i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-+*.5i)    :%-+*.5i|\n", 10, i);
    ft_printf("|test ft_printf (-+*.5i) :%-+*.5i|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (+*.*i)     :%+*.*i|\n", 10, 5, i);
    ft_printf("|test ft_printf (+*.*i)  :%+*.*i|\n", 10, 5, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0+*,*i)    :%0+*.*i|\n", 10, 5, i);
    ft_printf("|test ft_printf (0+*.*i) :%0+*.*i|\n", 10, 5, i);
    ft_printf("|---------------------------------|\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    printf("|test printf ()        :|\n");
    ft_printf("|test ft_printf ()     :|\n");
    ft_printf("|------------------------\\_\n");
    printf("|test printf (i)       :%i|\n", -i);
    ft_printf("|test ft_printf (i)    :%i|\n", -i);
    ft_printf("|--------------------------|\n");
    printf("|test printf (0i)      :%0i|\n", -i);
    ft_printf("|test ft_printf (0i)   :%0i|\n", -i);
    ft_printf("|--------------------------|\n");
    printf("|test printf ( i)      :% i|\n", -i);
    ft_printf("|test ft_printf ( i)   :% i|\n", -i);
    ft_printf("|--------------------------|\n");
    printf("|test printf (+i)      :%+i|\n", -i);
    ft_printf("|test ft_printf (+i)   :%+i|\n", -i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5i)      :%5i|\n", -i);
    ft_printf("|test ft_printf (5i)   :%5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05i)     :%05i|\n", -i);
    ft_printf("|test ft_printf (05i)  :%05i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5i)     :%-5i|\n", -i);
    ft_printf("|test ft_printf (-5i)  :%-5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( 5i)     :% 5i|\n", -i);
    ft_printf("|test ft_printf ( 5i)  :% 5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+5i)     :%+5i|\n", -i);
    ft_printf("|test ft_printf (+5i)  :%+5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( 05i)    :% 05i|\n", -i);
    ft_printf("|test ft_printf ( 05i) :% 05i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+05i)    :%+05i|\n", -i);
    ft_printf("|test ft_printf (+05i) :%+05i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf ( -5i)    :% -5i|\n", -i);
    ft_printf("|test ft_printf ( -5i) :% -5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (+-5i)    :%+-5i|\n", -i);
    ft_printf("|test ft_printf (+-5i) :%+-5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (0 5i)    :%0 5i|\n", -i);
    ft_printf("|test ft_printf (0 5i) :%0 5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (0+5i)    :%0+5i|\n", -i);
    ft_printf("|test ft_printf (0+5i) :%0+5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (- 5i)    :%- 5i|\n", -i);
    ft_printf("|test ft_printf (- 5i) :%- 5i|\n", -i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-+5i)    :%-+5i|\n", -i);
    ft_printf("|test ft_printf (-+5i) :%-+5i|\n", -i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-+*i)    :%-+*i|\n", 10, -i);
    ft_printf("|test ft_printf (-+*i) :%-+*i|\n", 10, -i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (+*i)     :%+*i|\n", 10, -i);
    ft_printf("|test ft_printf (+*i)  :%+*i|\n", 10, -i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0+*i)    :%0+*i|\n", 10, -i);
    ft_printf("|test ft_printf (0+*i) :%0+*i|\n", 10, -i);
    ft_printf("|---------------------------------|\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    printf("|test printf ()        :|\n");
    ft_printf("|test ft_printf ()     :|\n");
    ft_printf("|------------------------\\\n");
    printf("|test printf (c)       :%c|\n", c);
    ft_printf("|test ft_printf (c)    :%c|\n", c);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5c)      :%5c|\n", c);
    ft_printf("|test ft_printf (5c)   :%5c|\n", c);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5c)     :%-5c|\n", c);
    ft_printf("|test ft_printf (-5c)  :%-5c|\n", c);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-*c)     :%-*c|\n", 10, c);
    ft_printf("|test ft_printf (-*c)  :%-*c|\n", 10, c);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (*c)      :%*c|\n", 10, c);
    ft_printf("|test ft_printf (*c)   :%*c|\n", 10, c);
    ft_printf("|---------------------------------|\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    printf("|test printf ()        :|\n");
    ft_printf("|test ft_printf ()     :|\n");
    ft_printf("|------------------------\\____\n");
    printf("|test printf (s)       :%s|\n", s);
    ft_printf("|test ft_printf (s)    :%s|\n", s);
    ft_printf("|-----------------------------\\____\n");
    printf("|test printf (10s)      :%10s|\n", s);
    ft_printf("|test ft_printf (10s)   :%10s|\n", s);
    ft_printf("|----------------------------------|\n");
    printf("|test printf (-10s)     :%-10s|\n", s);
    ft_printf("|test ft_printf (-10s)  :%-10s|\n", s);
    ft_printf("|----------------------------------\\________\n");
    printf("|test printf (-*s)     :%-*s|\n", 20, s);
    ft_printf("|test ft_printf (-*s)  :%-*s|\n", 20, s);
    ft_printf("|-------------------------------------------|\n");
    printf("|test printf (*s)      :%*s|\n", 20, s);
    ft_printf("|test ft_printf (*s)   :%*s|\n", 20, s);
    ft_printf("|-------------------------------------------|\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    printf("|test printf ()        :|\n");
    ft_printf("|test ft_printf ()     :|\n");
    ft_printf("|------------------------\\\n");
    printf("|test printf (o)       :%o|\n", i);
    ft_printf("|test ft_printf (o)    :%o|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (0o)      :%0o|\n", i);
    ft_printf("|test ft_printf (0o)   :%0o|\n", i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5o)      :%5o|\n", i);
    ft_printf("|test ft_printf (5o)   :%5o|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05o)     :%05o|\n", i);
    ft_printf("|test ft_printf (05o)  :%05o|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5o)     :%-5o|\n", i);
    ft_printf("|test ft_printf (-5o)  :%-5o|\n", i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-*o)    :%-*o|\n", 10, i);
    ft_printf("|test ft_printf (-*o) :%-*o|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (*o)     :%*o|\n", 10, i);
    ft_printf("|test ft_printf (*o)  :%*o|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0*o)    :%0*o|\n", 10, i);
    ft_printf("|test ft_printf (0*o) :%0*o|\n", 10, i);
    ft_printf("|---------------------------------|\n");

    printf("|test printf (.5o)       :%.5o|\n", i);
    ft_printf("|test ft_printf (.5o)    :%.5o|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (0.5o)      :%0.5o|\n", i);
    ft_printf("|test ft_printf (0.5o)   :%0.5o|\n", i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5.5o)      :%5.5o|\n", i);
    ft_printf("|test ft_printf (5.5o)   :%5.5o|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05.5o)     :%05.5o|\n", i);
    ft_printf("|test ft_printf (05.5o)  :%05.5o|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5.5o)     :%-5.5o|\n", i);
    ft_printf("|test ft_printf (-5.5o)  :%-5.5o|\n", i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-*.5o)    :%-*.5o|\n", 10, i);
    ft_printf("|test ft_printf (-*.5o) :%-*.5o|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (*.*o)     :%*.*o|\n", 10, 5, i);
    ft_printf("|test ft_printf (*.*o)  :%*.*o|\n", 10, 5, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0*,*o)    :%0*.*o|\n", 10, 5, i);
    ft_printf("|test ft_printf (0*.*o) :%0*.*o|\n", 10, 5, i);
    ft_printf("|---------------------------------|\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    printf("|test printf ()        :|\n");
    ft_printf("|test ft_printf ()     :|\n");
    ft_printf("|------------------------\\\n");
    printf("|test printf (x)       :%x|\n", i);
    ft_printf("|test ft_printf (x)    :%x|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (0x)      :%0x|\n", i);
    ft_printf("|test ft_printf (0x)   :%0x|\n", i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5x)      :%5x|\n", i);
    ft_printf("|test ft_printf (5x)   :%5x|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05x)     :%05x|\n", i);
    ft_printf("|test ft_printf (05x)  :%05x|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5x)     :%-5x|\n", i);
    ft_printf("|test ft_printf (-5x)  :%-5x|\n", i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-*x)    :%-*x|\n", 10, i);
    ft_printf("|test ft_printf (-*x) :%-*x|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (*x)     :%*x|\n", 10, i);
    ft_printf("|test ft_printf (*x)  :%*x|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0*x)    :%0*x|\n", 10, i);
    ft_printf("|test ft_printf (0*x) :%0*x|\n", 10, i);
    ft_printf("|---------------------------------|\n");

    printf("|test printf (.5x)       :%.5x|\n", i);
    ft_printf("|test ft_printf (.5x)    :%.5x|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (0.5x)      :%0.5x|\n", i);
    ft_printf("|test ft_printf (0.5x)   :%0.5x|\n", i);
    ft_printf("|---------------------------\\\n");
    printf("|test printf (5.5x)      :%5.5x|\n", i);
    ft_printf("|test ft_printf (5.5x)   :%5.5x|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (05.5x)     :%05.5x|\n", i);
    ft_printf("|test ft_printf (05.5x)  :%05.5x|\n", i);
    ft_printf("|----------------------------|\n");
    printf("|test printf (-5.5x)     :%-5.5x|\n", i);
    ft_printf("|test ft_printf (-5.5x)  :%-5.5x|\n", i);
    ft_printf("|-----------------------------\\___\n");
    printf("|test printf (-*.5x)    :%-*.5x|\n", 10, i);
    ft_printf("|test ft_printf (-*.5x) :%-*.5x|\n", 10, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (*.*x)     :%*.*x|\n", 10, 5, i);
    ft_printf("|test ft_printf (*.*x)  :%*.*x|\n", 10, 5, i);
    ft_printf("|---------------------------------|\n");
    printf("|test printf (0*,*x)    :%0*.*x|\n", 10, 5, i);
    ft_printf("|test ft_printf (0*.*x) :%0*.*x|\n", 10, 5, i);
    ft_printf("|---------------------------------|\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    signed char sci = 125;
    unsigned char uci = 242;
    short ssi = 4269;
    unsigned short usi = 4269;
    long sli = 1147483647;
    unsigned long uli = 2494967295;
    long long slli = 5223372036854775807;
    unsigned long long ulli = 5223372036854775807;
    
    printf("|test printf (i)       :%i|\n", i);
    ft_printf("|test ft_printf (i)    :%i|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (li)       :%li|\n", sli);
    ft_printf("|test ft_printf (li)    :%li|\n", sli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (lli)       :%lli|\n", slli);
    ft_printf("|test ft_printf (lli)    :%lli|\n", slli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hi)       :%hi|\n", ssi);
    ft_printf("|test ft_printf (hi)    :%hi|\n", ssi);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hhi)       :%hhi|\n", sci);
    ft_printf("|test ft_printf (hhi)    :%hhi|\n", sci);
    ft_printf("|-------------------------|\n");
    printf("|test printf (o)       :%o|\n", i);
    ft_printf("|test ft_printf (o)    :%o|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (lo)       :%lo|\n", uli);
    ft_printf("|test ft_printf (lo)    :%lo|\n", uli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (llo)       :%llo|\n", ulli);
    ft_printf("|test ft_printf (llo)    :%llo|\n", ulli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (ho)       :%ho|\n", usi);
    ft_printf("|test ft_printf (ho)    :%ho|\n", usi);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hho)       :%hho|\n", uci);
    ft_printf("|test ft_printf (hho)    :%hho|\n", uci);
    ft_printf("|-------------------------|\n");
    printf("|test printf (x)       :%x|\n", i);
    ft_printf("|test ft_printf (x)    :%x|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (lx)       :%lx|\n", uli);
    ft_printf("|test ft_printf (lx)    :%lx|\n", uli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (llx)       :%llx|\n", ulli);
    ft_printf("|test ft_printf (llx)    :%llx|\n", ulli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hx)       :%hx|\n", usi);
    ft_printf("|test ft_printf (hx)    :%hx|\n", usi);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hhx)       :%hhx|\n", uci);
    ft_printf("|test ft_printf (hhx)    :%hhx|\n", uci);
    ft_printf("|-------------------------|\n");
    printf("|test printf (u)       :%u|\n", i);
    ft_printf("|test ft_printf (u)    :%u|\n", i);
    ft_printf("|-------------------------|\n");
    printf("|test printf (lu)       :%lu|\n", uli);
    ft_printf("|test ft_printf (lu)    :%lu|\n", uli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (llu)       :%llu|\n", ulli);
    ft_printf("|test ft_printf (llu)    :%llu|\n", ulli);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hu)       :%hu|\n", usi);
    ft_printf("|test ft_printf (hu)    :%hu|\n", usi);
    ft_printf("|-------------------------|\n");
    printf("|test printf (hhu)       :%hhu|\n", uci);
    ft_printf("|test ft_printf (hhu)    :%hhu|\n", uci);
    ft_printf("|-------------------------|\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    wint_t wtc = 142;
    
    printf("|test printf (c)       :%c|\n", c);
    ft_printf("|test ft_printf (c)    :%c|\n", c);
    ft_printf("-------------------------\n");
    printf("|test printf (lc)       :%lc|\n", wtc);
    ft_printf("|test ft_printf (lc)    :%lc|\n", wtc);
    ft_printf("-------------------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    printf("|test printf (d)     :%d|\n", 0);
    ft_printf("|test ft_printf  (d) :%d|\n", 0);
    ft_printf("-------------------------\n");
    printf("|test printf (d)     :%d|\n", i);
    ft_printf("|test ft_printf  (d) :%d|\n", i);
    ft_printf("-------------------------\n");
    printf("|test printf (.d)    :%.d|\n", 0);
    ft_printf("|test ft_printf (.d) :%.d|\n", 0);
    ft_printf("-------------------------\n");
    printf("|test printf (.d)    :%.d|\n", i);
    ft_printf("|test ft_printf (.d) :%.d|\n", i);
    ft_printf("-------------------------\n");
    printf("|test printf (.2d)   :%.2d|\n", 0);
    ft_printf("|test ft_printf (.2d):%.2d|\n", 0);
    ft_printf("-------------------------\n");
    printf("|test printf (.2d)   :%.2d|\n", i);
    ft_printf("|test ft_printf (.2d):%.2d|\n", i);
    ft_printf("-------------------------\n");
    printf("|%0*.d|\n", -2, 0);
    ft_printf("|%0*.d|\n", -2, 0);
    ft_printf("-------------------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    ft_printf("-------------------------\n");
    printf("|%011.1d|\n", UINT_MAX + 1);
    ft_printf("|%011.1d|\n", UINT_MAX + 1);
    ft_printf("-------------------------\n");
    printf("|%09.0d|\n", UINT_MAX);
    ft_printf("|%09.0d|\n", UINT_MAX);
    ft_printf("-------------------------\n");
    printf("|%010.0d|\n", UINT_MAX);
    ft_printf("|%010.0d|\n", UINT_MAX);
    ft_printf("-------------------------\n");
    printf("|%011.0d|\n", UINT_MAX);
    ft_printf("|%011.0d|\n", UINT_MAX);
    ft_printf("-------------------------\n");
    printf("|%09.0d|\n", UINT_MAX + 1);
    ft_printf("|%09.0d|\n", UINT_MAX + 1);
    ft_printf("-------------------------\n");
    printf("|%010.0d|\n", UINT_MAX + 1);
    ft_printf("|%010.0d|\n", UINT_MAX + 1);
    ft_printf("-------------------------\n");
    printf("|%011.0d|\n", UINT_MAX + 1);
    ft_printf("|%011.0d|\n", UINT_MAX + 1);
    ft_printf("-------------------------\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    ft_printf("-------------------------\n");
    printf("|%-3.2u %10.42u|\n", 1, -1);
    ft_printf("|%-3.2u %10.42u|\n", 1, -1);
    ft_printf("-------------------------\n");
    printf("|%10.42u|\n", -1);
    ft_printf("|%10.42u|\n", -1);
    ft_printf("-------------------------\n");
    printf("|%-3.2u|\n", -1);
    ft_printf("|%-3.2u|\n", -1);
    ft_printf("-------------------------\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    ft_printf("-------------------------\n");
    printf("|%*.s %.1s|\n", 10, "123", "4567");
    ft_printf("|%*.s %.1s|\n", 10, "123", "4567");
    ft_printf("-------------------------\n");
    printf("|%*.s|\n", 10, "123");
    ft_printf("|%*.s|\n", 10, "123");
    ft_printf("-------------------------\n");
    printf("|%.1s|\n", "4567");
    ft_printf("|%.1s|\n", "4567");
    ft_printf("-------------------------\n");
    printf("|%.10s|\n", "4567");
    ft_printf("|%.10s|\n", "4567");
    ft_printf("-------------------------\n");
    printf("|%*.*s|\n", 10, -2, "coucou");
    ft_printf("|%*.*s|\n", 10, -2, "coucou");
    ft_printf("-------------------------\n");
    printf("|%*.*s|\n", 10, 2, "coucou");
    ft_printf("|%*.*s|\n", 10, 2, "coucou");
    ft_printf("-------------------------\n");
    // printf("|%-3.s|\n", NULL);
    // ft_printf("|%-3.s|\n", NULL);
    // ft_printf("-------------------------\n");
    // printf("|%-3.1s|\n", NULL);
    // ft_printf("|%-3.1s|\n", NULL);
    // ft_printf("-------------------------\n");
    // printf("|%.*s|\n", -2, NULL);
    // ft_printf("|%.*s|\n", -2, NULL);
    // ft_printf("-------------------------\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    ft_printf("-------------------------\n");
    printf("|%p|\n", NULL);
    ft_printf("|%p|\n", NULL);
    ft_printf("-------------------------\n");
    printf("|%p|\n", &i);
    ft_printf("|%p|\n", &i);
    ft_printf("-------------------------\n");
    printf("|%p|\n", &c);
    ft_printf("|%p|\n", &c);
    ft_printf("-------------------------\n");
    printf("|%p|\n", s);
    ft_printf("|%p|\n", s);
    ft_printf("-------------------------\n");
    printf("|%p|\n", &s);
    ft_printf("|%p|\n", &s);
    ft_printf("-------------------------\n");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    double d1 = 2.51;
    double d2 = 2;
    double d3 = 0;

    ft_printf("-------------------------\n");
    printf("|%f|\n", d1);
    ft_printf("|%f|\n", d1);
    ft_printf("-------------------------\n");
    printf("|%.f|\n", d1);
    ft_printf("|%.f|\n", d1);
    ft_printf("-------------------------\n");
    printf("|%.5f|\n", d1);
    ft_printf("|%.5f|\n", d1);
    ft_printf("-------------------------\n");
    printf("|%.0f|\n", d1);
    ft_printf("|%.0f|\n", d1);
    ft_printf("-------------------------\n");
    printf("|%f|\n", d2);
    ft_printf("|%f|\n", d2);
    ft_printf("-------------------------\n");
    printf("|%.f|\n", d2);
    ft_printf("|%.f|\n", d2);
    ft_printf("-------------------------\n");
    printf("|%.5f|\n", d2);
    ft_printf("|%.5f|\n", d2);
    ft_printf("-------------------------\n");
    printf("|%.0f|\n", d2);
    ft_printf("|%.0f|\n", d2);
    ft_printf("-------------------------\n");
    printf("|%f|\n", d3);
    ft_printf("|%f|\n", d3);
    ft_printf("-------------------------\n");
    printf("|%.f|\n", d3);
    ft_printf("|%.f|\n", d3);
    ft_printf("-------------------------\n");
    printf("|%.5f|\n", d3);
    ft_printf("|%.5f|\n", d3);
    ft_printf("-------------------------\n");
    printf("|%.0f|\n", d3);
    ft_printf("|%.0f|\n", d3);
    ft_printf("-------------------------\n");
    printf("|%f %f|\n", 42.0, -42.0);
    ft_printf("|%f %f|\n", 42.0, -42.0);
    ft_printf("-------------------------\n");
    printf("|%07.f %08.1f %09.2f|\n", 0.0, -1.0, 42.0);
    ft_printf("|%07.f %08.1f %09.2f|\n", 0.0, -1.0, 42.0);
    ft_printf("-------------------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    ft_printf("-------------------------\n");
    printf("|   printf( .0f-> 1.5) :% .0f|\n", 1.5);
    ft_printf("|ft_printf( .0f-> 1.5) :% .0f|\n", 1.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f-> 2.5) :% .0f|\n", 2.5);
    ft_printf("|ft_printf( .0f-> 2.5) :% .0f|\n", 2.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f-> 3.5) :% .0f|\n", 3.5);
    ft_printf("|ft_printf( .0f-> 3.5) :% .0f|\n", 3.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f-> 4.5) :% .0f|\n", 4.5);
    ft_printf("|ft_printf( .0f-> 4.5) :% 2.0f|\n", 4.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f->-1.5) :% .0f|\n", -1.5);
    ft_printf("|ft_printf( .0f->-1.5) :% .0f|\n", -1.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f->-2.5) :% .0f|\n", -2.5);
    ft_printf("|ft_printf( .0f->-2.5) :% .0f|\n", -2.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f->-3.5) :% .0f|\n", -3.5);
    ft_printf("|ft_printf( .0f->-3.5) :% .0f|\n", -3.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f->-3.5) :% .0f|\n", -4.5);
    ft_printf("|ft_printf( .0f->-3.5) :% .0f|\n", -4.5);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f-> 1.51) :% .0f|\n", 1.51);
    ft_printf("|ft_printf( .0f-> 1.51) :% .0f|\n", 1.51);
    ft_printf("---------------------------\n");
    printf("|   printf( .0f-> 2.51) :% .0f|\n", 2.51);
    ft_printf("|ft_printf( .0f-> 2.51) :% .0f|\n", 2.51);
    ft_printf("---------------------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    ft_printf("-------------------------\n");
    printf("|%f %f|\n", -2147483648 * 1.0, 2147483647 * 1.0);
    ft_printf("|%f %f|\n", -2147483648 * 1.0, 2147483647 * 1.0);
    ft_printf("-------------------------\n");
    printf("|%f %f|\n", INT_MIN * 1.0, INT_MAX * 1.0);
    ft_printf("|%f %f|\n", INT_MIN * 1.0, INT_MAX * 1.0);
    ft_printf("---------------------------\n");
    printf("|%f %f|\n", INT_MIN * 1.0 - 1, INT_MAX * 1.0 + 1);
    ft_printf("|%f %f|\n", INT_MIN * 1.0 - 1, INT_MAX * 1.0 + 1);
    ft_printf("---------------------------\n");
    printf("|%f %f|\n", INT_MIN * 1.0 + 1, INT_MAX * 1.0 - 1);
    ft_printf("|%f %f|\n", INT_MIN * 1.0 + 1, INT_MAX * 1.0 - 1);
    ft_printf("---------------------------\n");
    printf("|%f %f|\n", -9223372036854775808.0, 9223372036854775808.0);
    ft_printf("|%f %f|\n", -9223372036854775808.0, 9223372036854775808.0);
    ft_printf("---------------------------\n");
    printf("|%f %f|\n", LONG_MIN * 1.0, LONG_MAX * 1.0);
    ft_printf("|%f %f|\n", LONG_MIN * 1.0, LONG_MAX * 1.0);
    ft_printf("---------------------------\n");
    printf("|%f %f|\n", LONG_MIN * 1.0 - 1, LONG_MAX * 1.0 + 1);
    ft_printf("|%f %f|\n", LONG_MIN * 1.0 - 1, LONG_MAX * 1.0 + 1);
    ft_printf("---------------------------\n");
    printf("|%f %f|\n", LONG_MIN * 1.0 + 1, LONG_MAX * 1.0 - 1);
    ft_printf("|%f %f|\n", LONG_MIN * 1.0 + 1, LONG_MAX * 1.0 - 1);
    ft_printf("---------------------------\n");
    printf("|%10f|\n", 1.0 / 0);
    ft_printf("|%10f|\n", 1.0 / 0);
    ft_printf("-------------------------\n");
    printf("|%020.20f|\n", 1.0 / 0);
    ft_printf("|%020.20f|\n", 1.0 / 0);
    ft_printf("-------------------------\n");
    printf("|%020.20f|\n", 0.0 / 0);
    ft_printf("|%020.20f|\n", 0.0 / 0);
    ft_printf("-------------------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    printf("------------ƀ-ɏ-࿚-------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'ƀ');
    ft_printf("|%lc|\n", u'ƀ');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'ɏ');
    ft_printf("|%lc|\n", u'ɏ');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'ɐ');
    ft_printf("|%lc|\n", u'ɐ');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'ʯ');
    ft_printf("|%lc|\n", u'ʯ');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'ʰ');
    ft_printf("|%lc|\n", u'ʰ');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'˿');
    ft_printf("|%lc|\n", u'˿');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'ୟ');
    ft_printf("|%lc|\n", u'ୟ');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'௫');
    ft_printf("|%lc|\n", u'௫');
    ft_printf("-------------------------\n");
    printf("|%lc|\n", u'࿚');
    ft_printf("|%lc|\n", u'࿚');
    ft_printf("-------------------------\n");
    
    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");
    
    ft_printf("------------ƀ-ɏ-࿚-------------\n");

    printf("|st120 %*s|\n", 100, "hello");
    ft_printf("|st120 %*s|\n", 100, "hello");

    ft_printf("\n");
    ft_printf("\n");
    ft_printf("\n");

    printf("|ultimate2 %*d %*s %*x %*X %*i %*u|\n", 1, 5000, 1, "hey", 10, 54700, 1, 300, 10000, -55, 1, -60);
    ft_printf("|ultimate2 %*d %*s %*x %*X %*i %*u|\n", 1, 5000, 1, "hey", 10, 54700, 1, 300, 10000, -55, 1, -60);
}
